Repository AdoptaUnJuniorPlatform/GDGAranjuez, pull requests merged in 2025-09, with the labels that each got.

#197 Sponsors were changed.
  src/components/Patrocinadores.astro
Labels: styles / design, content

#198 192 add speakers
  public/speakers/antonio-leiva.jpg
  public/speakers/estefania-peromingo.jpg
  public/speakers/irene-ruiz-pozo.jpg
  public/speakers/maria-del-carmen-tajuelo.jpg
  public/speakers/maximo-fernandez-nunez.jpg
  public/speakers/moises-martinez.jpg
  public/speakers/nacho-fernandez-diez.png
  public/speakers/pablo-rodriguez-tembleco.jpg
  public/speakers/sergi-olives.jpg
  src/components/Card.astro
  src/components/PonentesSection.astro
Labels: enhancement, styles / design, content

#204 feat: :sparkles: Issue 200 - Update Schedule
  src/components/AgendaDevFest.astro
  src/components/AgendaSection.astro
Labels: must have, content

#207 Release 2025-09-02T17:08
  public/colaboradores/elmago.jpg
  public/colaboradores/jorge-castillo.jpg
  public/colaboradores/manu-fosela.jpg
  public/colaboradores/nicolas.jpg
  public/desarrolladores/AngieMIV.webp
  public/desarrolladores/BelenSuarez.webp
  public/desarrolladores/GloriaMonzo.webp
  public/desarrolladores/JRamonCarralero.webp
  public/desarrolladores/ManuelTomasino.webp
  public/desarrolladores/MarlonVelasquez.webp
  public/desarrolladores/RaulGambalonga.webp
  public/speakers/antonio-leiva.jpg
  public/speakers/estefania-peromingo.jpg
  public/speakers/irene-ruiz-pozo.jpg
  public/speakers/maria-del-carmen-tajuelo.jpg
  public/speakers/maximo-fernandez-nunez.jpg
  public/speakers/moises-martinez.jpg
  public/speakers/nacho-fernandez-diez.png
  public/speakers/pablo-rodriguez-tembleco.jpg
  public/speakers/sergi-olives.jpg
  src/components/AgendaDevFest.astro
  src/components/AgendaSection.astro
  src/components/Card.astro
  src/components/Colaborador.astro
  src/components/ColaboradorSection.astro
  src/components/Countdown.astro
  src/components/DevelopersSection.astro
  src/components/Organizador.astro
  src/components/OrganizadoresSection.astro
  src/components/Patrocinadores.astro
  src/components/Ponente.astro
  src/components/PonentesSection.astro
  src/components/Section.astro
  src/components/Socials.astro
  src/pages/index.astro
Labels: enhancement, must have, content

#209 refactor: AgendaDevFest.astro > TCB in 16:35's talk
  src/components/AgendaDevFest.astro
Labels: must have, content
