Repository AdoptaUnJuniorPlatform/GDGAranjuez, pull requests merged in 2025-06, with the labels that each got.

#146 Commented PostSection in index.astro and Blog in Navbar
  src/components/Navbar.astro
  src/pages/index.astro
Labels: Must have

#150 Reorder sponsors by tier
  src/components/Patrocinadores.astro
Labels: enhancement, styles / design, content

#155 feat(footer): add codigo de conducta
  src/components/Footer.astro
Labels: enhancement, content

#158 151 clean placeholders in sections
  public/colaboradores/angiemiv.jpg
  src/components/AgendaDevFest.astro
  src/components/CharlasSection.astro
  src/components/Colaborador.astro
  src/components/ColaboradorSection.astro
  src/components/DetallesEvento.astro
  src/components/Organizador.astro
  src/components/OrganizadoresSection.astro
  src/components/Ponente.astro
  src/components/PonentesSection.astro
  src/components/Socials.astro
Labels: enhancement, styles / design, content

#143 feat(posts): add placeholder functionality for unpublished posts
  src/components/PostCard.astro
  src/components/PostsSection.astro
  src/content/_template/_README.md
  src/content/config.ts
  src/content/posts/first-post.md
  src/content/posts/second-post.md
  src/pages/blog.astro
  src/pages/blog/[...slug].astro
  src/pages/index.astro
Labels: styles / design, must have, content
